###
# https://www.chezmoi.io/user-guide/include-files-from-elsewhere/
# To refresh submdules (git pull) use --refresh-externals option (e.g. `chezmoi apply -R`)
# Feature only git clone/pull, it does not git push
###
{{- $custom := .zsh.ZSH_CUSTOM }}

["{{- .zsh.ZSH }}"]
    type = "git-repo"
    url = "{{- .zsh.ZSH_SRC }}"
    stripComponents = 1
    refreshPeriod = "168h"
    ["{{- .zsh.ZSH }}".clone]
        args = ["--depth=1"]

{{- if eq .zsh.ZSH ".oh-my-zsh" }}
# omz custom plugins need to be installed
{{ range $key, $value := .plugins }}
["{{ $custom }}/plugins/{{ $key }}"]
    type = "git-repo"
    url = "git@github.com:{{ $value }}.git"
    stripComponents = 1
    refreshPeriod = "168h"
{{ end }}

{{- end }}

# themes
{{- if eq .zsh.ZSH_THEME "powerlevel10k/powerlevel10k" }}
["{{ $custom }}/themes/powerlevel10k"]
    type = "git-repo"
    url = "git@github.com:romkatv/powerlevel10k.git"
    stripComponents = 1
    refreshPeriod = "168h"
{{- end }}

{{- if (index (default dict .tools) "vim_runtime") }}
# first time setups require init command:
# `sh ~/.vim_runtime/install_awesome_vimrc.sh`
[".vim_runtime"]
    type = "git-repo"
    url = "git@github.com:amix/vimrc.git"
    refreshPeriod = "336h"
{{- end }}

{{- if (index (default dict .tools) "drunk_zsh_history") }}
# Personal Command History - 
["{{ .xdg.CONFIG }}/drunk-zsh-history"]
    type = "git-repo"
    url = "git@github.com:MikeTayC/drunk-zsh-history.git"
    refreshPeriod = "336h"
{{- end }}
