###
# https://www.chezmoi.io/user-guide/include-files-from-elsewhere/
# To refresh submdules (git pull) use --refresh-externals option (e.g. `chezmoi apply -R`)
# Feature only git clone/pull, it does not git push
###
["{{- .zsh.ZSH }}"]
    type = "git-repo"
    url = "{{- .zsh.ZSH_SRC }}"
    stripComponents = 1
    refreshPeriod = "168h"
    ["{{- .zsh.ZSH }}".clone]
        args = ["--depth=1"]


{{ if eq .zsh.ZSH ".oh-my-zsh" }}
["{{ .zsh.ZSH_CUSTOM }}/plugins/fast-syntax-highlighting"]
    type = "git-repo"
    url = "git@github.com:zdharma-continuum/fast-syntax-highlighting.git"
    stripComponents = 1
    refreshPeriod = "168h"

["{{ .zsh.ZSH_CUSTOM }}/plugins/history-sync"]
    type = "git-repo"
    url = "git@github.com:wulfgarpro/history-sync.git"
    stripComponents = 1
    refreshPeriod = "168h"

["{{ .zsh.ZSH_CUSTOM }}/plugins/zsh-eza"]
    type = "git-repo"
    url = "git@github.com:z-shell/zsh-eza.git"
    stripComponents = 1
    refreshPeriod = "168h"

["{{ .zsh.ZSH_CUSTOM }}/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "git@github.com:zsh-users/zsh-autosuggestions.git"
    stripComponents = 1
    refreshPeriod = "168h"
    
["{{ .zsh.ZSH_CUSTOM }}/plugins/fzf-tab"]
    type = "git-repo"
    url = "git@github.com:Aloxaf/fzf-tab.git"
    stripComponents = 1
    refreshPeriod = "168h"
{{- end }}

# themes
{{- if eq .zsh.ZSH_THEME "powerlevel10k/powerlevel10k" }}
["{{ .zsh.ZSH_CUSTOM }}/themes/powerlevel10k"]
    type = "git-repo"
    url = "git@github.com:romkatv/powerlevel10k.git"
    exact = true
    stripComponents = 1
{{- end }}

{{- if (index (default dict .tools) "vim_runtime") }}
# first time setups require init command:
# `sh ~/.vim_runtime/install_awesome_vimrc.sh`
[".vim_runtime"]
    type = "git-repo"
    url = "git@github.com:amix/vimrc.git"
    refreshPeriod = "336h"
{{- end }}

{{- if (index (default dict .tools) "drunk_zsh_history") }}
# Personal Command History - 
["{{ .xdg.CONFIG }}/drunk-zsh-history"]
    type = "git-repo"
    url = "git@github.com:MikeTayC/drunk-zsh-history.git"
    refreshPeriod = "336h"
{{- end }}
